### /Get all cars 1
GET  http://localhost:9090/api/v1/allcars

#### Get all orders 2
GET http://localhost:9090/api/v1/orders

### 3post orders custom-controller - the customer dont have any orders
POST http://localhost:9090/api/v1/myorders/

Content-Type: application/json
{
  "id": 3
}

### 4Get all customers
GET http://localhost:9090/api/v1/customers

### 5Delete customers by ID
DELETE http://localhost:9090/api/v1/deletecustomer


Content-Type: application/json
{
  "id": 3
}

### 6Add customer
POST http://localhost:9090/api/v1/addcustomer
Content-Type: application/json

{
  "username": "string",
  "name": "string",
  "address": "string",
  "email": "string",
  "phoneNumber": "string"
}

### 7Cancel orders
PUT http://localhost:9090/api/v1/cancelorder
Content-Type: application/json

{
  "bookingId": 1
}


### 8Update a order
POST  http://localhost:9090/api/v1/myorders
Content-Type: application/json

{
  "id": 1
}
### 9 Customer see cars that is not booked
GET   http://localhost:9090/api/v1/cars


### 10 Update car 
GET http://localhost:9090/api/v1/updatecar
Content-Type: application/json
{
  "id": 1,
  "pricePerDay": 0,
  "fabric": "string",
  "model": "string",
  "registrationNumber": "string",
  "isBooked": true
}



